config/routes.rb
Rails.application.routes.draw do
  resources :shipment_locations
  resources :brokerage_jobs
  root 'brokerage_jobs#index'
  
  constraints subdomain: "hooks" do
    post '/:webhook_name' => 'webhooks#receive', as: :receive_webhooks
  end

  # if Rails.env.development?
  #   mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  # end

  post "/graphql", to: "graphql#execute"

end

app/models/brokerage_job.rb
class BrokerageJob
  include Mongoid::Document
  include Mongoid::Timestamps 

  field :job, type: String
  field :shipment, type: String
  field :status, type: String

  has_many :shipment_locations, dependent: :destroy
end

app/models/shipment_location.rb
class ShipmentLocation
  include Mongoid::Document
  include Mongoid::Timestamps 

  field :shipment, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  belongs_to :BrokerageJob
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brokerage_jobs_controller.rb
class BrokerageJobsController < ApplicationController
  before_action :set_brokerage_job, only: %i[ show edit update destroy ]

  # GET /brokerage_jobs or /brokerage_jobs.json
  def index
    @brokerage_jobs = BrokerageJob.all
  end

  # GET /brokerage_jobs/1 or /brokerage_jobs/1.json
  def show
  end

  # GET /brokerage_jobs/new
  def new
    @brokerage_job = BrokerageJob.new
  end

  # GET /brokerage_jobs/1/edit
  def edit
  end

  # POST /brokerage_jobs or /brokerage_jobs.json
  def create
    @brokerage_job = BrokerageJob.new(brokerage_job_params)

    respond_to do |format|
      if @brokerage_job.save
        format.html { redirect_to @brokerage_job, notice: "Brokerage job was successfully created." }
        format.json { render :show, status: :created, location: @brokerage_job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brokerage_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brokerage_jobs/1 or /brokerage_jobs/1.json
  def update
    respond_to do |format|
      if @brokerage_job.update(brokerage_job_params)
        format.html { redirect_to @brokerage_job, notice: "Brokerage job was successfully updated." }
        format.json { render :show, status: :ok, location: @brokerage_job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brokerage_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brokerage_jobs/1 or /brokerage_jobs/1.json
  def destroy
    @brokerage_job.destroy
    respond_to do |format|
      format.html { redirect_to brokerage_jobs_url, notice: "Brokerage job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brokerage_job
      @brokerage_job = BrokerageJob.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brokerage_job_params
      params.require(:brokerage_job).permit(:job, :shipment, :status)
    end
end

app/controllers/shipment_locations_controller.rb
class ShipmentLocationsController < ApplicationController
  before_action :set_shipment_location, only: %i[ show edit update destroy ]

  # GET /shipment_locations or /shipment_locations.json
  def index
    @shipment_locations = ShipmentLocation.all
  end

  # GET /shipment_locations/1 or /shipment_locations/1.json
  def show
  end

  # GET /shipment_locations/new
  def new
    @shipment_location = ShipmentLocation.new
  end

  # GET /shipment_locations/1/edit
  def edit
  end

  # POST /shipment_locations or /shipment_locations.json
  def create
    @shipment_location = ShipmentLocation.new(shipment_location_params)

    respond_to do |format|
      if @shipment_location.save
        format.html { redirect_to @shipment_location, notice: "Shipment location was successfully created." }
        format.json { render :show, status: :created, location: @shipment_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipment_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipment_locations/1 or /shipment_locations/1.json
  def update
    respond_to do |format|
      if @shipment_location.update(shipment_location_params)
        format.html { redirect_to @shipment_location, notice: "Shipment location was successfully updated." }
        format.json { render :show, status: :ok, location: @shipment_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shipment_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipment_locations/1 or /shipment_locations/1.json
  def destroy
    @shipment_location.destroy
    respond_to do |format|
      format.html { redirect_to shipment_locations_url, notice: "Shipment location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment_location
      @shipment_location = ShipmentLocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shipment_location_params
      params.require(:shipment_location).permit(:shipment, :latitude, :longitude, :BrokerageJob_id)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def receive
    if request.headers['Content-Type'] == 'application/json'
      data = JSON.parse(request.body.read)
    else
      data = params.as_json
    end

    Webhook::Received.save(data: data, webhook: params[:webhook_name])

    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brokerage_jobs_helper.rb
module BrokerageJobsHelper
end

app/helpers/shipment_locations_helper.rb
module ShipmentLocationsHelper
end

app/views/brokerage_jobs/_form.html.erb
<%= form_with(model: brokerage_job) do |form| %>
  <% if brokerage_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brokerage_job.errors.count, "error") %> prohibited this brokerage_job from being saved:</h2>

      <ul>
        <% brokerage_job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :job %>
    <%= form.text_field :job %>
  </div>

  <div class="field">
    <%= form.label :shipment %>
    <%= form.text_field :shipment %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brokerage_jobs/edit.html.erb
<h1>Editing Brokerage Job</h1>

<%= render 'form', brokerage_job: @brokerage_job %>

<%= link_to 'Show', @brokerage_job %> |
<%= link_to 'Back', brokerage_jobs_path %>

app/views/brokerage_jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brokerage Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Job</th>
      <th>Shipment</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brokerage_jobs.each do |brokerage_job| %>
      <tr>
        <td><%= brokerage_job.job %></td>
        <td><%= brokerage_job.shipment %></td>
        <td><%= brokerage_job.status %></td>
        <td><%= link_to 'Show', brokerage_job %></td>
        <td><%= link_to 'Edit', edit_brokerage_job_path(brokerage_job) %></td>
        <td><%= link_to 'Destroy', brokerage_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brokerage Job', new_brokerage_job_path %>

app/views/brokerage_jobs/new.html.erb
<h1>New Brokerage Job</h1>

<%= render 'form', brokerage_job: @brokerage_job %>

<%= link_to 'Back', brokerage_jobs_path %>

app/views/brokerage_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @brokerage_job.job %>
</p>

<p>
  <strong>Shipment:</strong>
  <%= @brokerage_job.shipment %>
</p>

<p>
  <strong>Status:</strong>
  <%= @brokerage_job.status %>
</p>

<%= link_to 'Edit', edit_brokerage_job_path(@brokerage_job) %> |
<%= link_to 'Back', brokerage_jobs_path %>

<section class="section shipment_locations">
  <div class="container">
    <h2 class="subtitle is-5">
      <strong><%= @brokerage_job.shipment_locations.count %></strong> 
      <% if @brokerage_job.shipment_locations.count == 0 || 1 %>
        shipment location
      <% else %>
        shipment locations 
      <% end %>
    </h2>
    <table>
  <thead>
    <tr>
      <th>Shipment</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Brokeragejob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brokerage_job.shipment_locations.each do |shipment_location| %>
      <tr>
        <td><%= shipment_location.shipment %></td>
        <td><%= shipment_location.latitude %></td>
        <td><%= shipment_location.longitude %></td>
        <td><%= shipment_location.BrokerageJob_id %></td>
        <td><%= link_to 'Show', shipment_location %></td>
        <td><%= link_to 'Edit', edit_shipment_location_path(shipment_location) %></td>
        <td><%= link_to 'Destroy', shipment_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <div class="shipment_location-form">
      <hr />
      <h3 class="subtitle is-3">Enter New Location</h3>
      <%= render partial: 'shipment_locations/form', locals: { shipment_location: @brokerage_job.shipment_locations.build } %>
    </div>
  </div>
</section>

<hr />

Current Location of <strong> <%= @brokerage_job.job %> </strong>

<table>
  <thead>
    <tr>
      <th>Shipment</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Brokeragejob</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tr>
    <td><%= @brokerage_job.shipment_locations[-2].shipment %></td>
    <td><%= @brokerage_job.shipment_locations[-2].latitude %></td>
    <td><%= @brokerage_job.shipment_locations[-2].longitude %></td>
    <td><%= @brokerage_job.shipment_locations[-2].BrokerageJob_id %></td>
  </tr>
</table>

<%= link_to shipment_locations_path, class: '#', :remote => true do %>
  <i class="icon-trash">Current Location</i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebhookRailsMongoHeroku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shipment_locations/_form.html.erb
<%= form_with(model: shipment_location) do |form| %>
  <% if shipment_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment_location.errors.count, "error") %> prohibited this shipment_location from being saved:</h2>

      <ul>
        <% shipment_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shipment %>
    <%= form.text_field :shipment %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :BrokerageJob_id %>
    <%= form.hidden_field :BrokerageJob_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shipment_locations/_shipment_location.html.erb
<p>
  <strong><%= shipment_location.shipment %>:</strong>
  <%= shipment_location.message %>
<br>
<%= link_to 'Delete', [shipment_location],
  method: :delete,
  class: "#",
  data: { confirm: 'Are you sure?' } %>
</p>

app/views/shipment_locations/edit.html.erb
<h1>Editing Shipment Location</h1>

<%= render 'form', shipment_location: @shipment_location %>

<%= link_to 'Show', @shipment_location %> |
<%= link_to 'Back', shipment_locations_path %>

app/views/shipment_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipment Locations</h1>

<table>
  <thead>
    <tr>
      <th>Shipment</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Brokeragejob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipment_locations.each do |shipment_location| %>
      <tr>
        <td><%= shipment_location.shipment %></td>
        <td><%= shipment_location.latitude %></td>
        <td><%= shipment_location.longitude %></td>
        <td><%= shipment_location.BrokerageJob_id %></td>
        <td><%= link_to 'Show', shipment_location %></td>
        <td><%= link_to 'Edit', edit_shipment_location_path(shipment_location) %></td>
        <td><%= link_to 'Destroy', shipment_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment Location', new_shipment_location_path %>

app/views/shipment_locations/new.html.erb
<h1>New Shipment Location</h1>

<%= render 'form', shipment_location: @shipment_location %>

<%= link_to 'Back', shipment_locations_path %>

app/views/shipment_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipment:</strong>
  <%= @shipment_location.shipment %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @shipment_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @shipment_location.longitude %>
</p>

<p>
  <strong>Brokeragejob:</strong>
  <%= @shipment_location.BrokerageJob_id %>
</p>

<%= link_to 'Edit', edit_shipment_location_path(@shipment_location) %> |
<%= link_to 'Back', shipment_locations_path %>